name: OS test
on: [push]
jobs:
    OSTest:
        strategy:
            matrix:
                os: [windows-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v7
            - name: Install the latest version of uv
              uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
            - run: uv sync
            - run: uv run python -m sysinv.main
