name: OS test
on: [push]
jobs:
    OSTest:
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v7
            - uses: actions/setup-python@v7
              with:
                  python-version: "3.13"
            - run: python main.py
